# Change these first
owner: doctorfree # Your GitHub organization or username, where this repository lives
repo: subdomains # The name of this repository

sites:
  - name: uptime.ronrecord.com
    url: https://uptime.ronrecord.com
  - name: asciigames.neoman.dev
    url: https://asciigames.neoman.dev
  - name: astronvim.lazyman.dev
    url: https://astronvim.lazyman.dev
  - name: ide.lazyman.dev
    url: https://ide.lazyman.dev
  - name: lazyvim.lazyman.dev
    url: https://lazyvim.lazyman.dev
  - name: lunarvim.lazyman.dev
    url: https://lunarvim.lazyman.dev
  - name: nvchad.lazyman.dev
    url: https://nvchad.lazyman.dev
  - name: webdev.lazyman.dev
    url: https://webdev.lazyman.dev
  - name: archive.ronrecord.com
    url: https://archive.ronrecord.com
  - name: fractals.ronrecord.com
    url: https://fractals.ronrecord.com
  - name: blog.ronrecord.com
    url: https://blog.ronrecord.com
  - name: themes.ronrecord.com
    url: https://doctorfree.github.io/google-chrome-themes
    icon: https://raw.githubusercontent.com/doctorfree/subdomains/master/assets/dummy.ico

assignees: # Users to assign downtime issues (optional)
  - doctorfree

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: lazyman.dev
  baseUrl: /subdomains
  logoUrl: https://raw.githubusercontent.com/doctorfree/subdomains/master/assets/upptime-icon.svg
  name: Status
  introTitle: "Open source website uptime monitor"
  introMessage: Websites status page using **real-time** data from my [GitHub repository](https://github.com/doctorfree/subdomains)
  navbar:
    - title: Repository
      href: https://github.com/$OWNER/$REPO
    - title: Profile
      href: https://github.com/$OWNER

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration